### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by fabianschwarzfritz** [ashkulz/committers.top#2]
Hi, 

Thanks so much for taking up this project ! Very nice :)

Is there anything you'd need help with? I would be happy to support this where I can.

Cheers Fabian

**Comment by ashkulz** [comment]
Not really, as you can see from the [website branch](https://github.com/ashkulz/committers.top/commits/website) it's fully automated via the [weekly_update workflow](https://github.com/ashkulz/committers.top/actions/workflows/weekly_update.yml). There are some intermittent timeouts due to rate limits, and it takes a full 2 days to run -- but I don't think much can be done for that :man_shrugging:

I've merged most of the pending PRs and added comments on most issues, feel free to send a PR for anything I've missed :+1:
