### ISSUE TITLE
Syria data wasn't updated

### ISSUE THREAD

**Issue by karam-mustafa** [ashkulz/committers.top#4]
Hi, the Syrian statistics was not updated since 17-4, when they will update ?.

**Comment by ashkulz** [comment]
@karam-mustafa the data gets updated every weekend, so that's expected -- data will be up to a week old. If you see [the data files](https://github.com/ashkulz/committers.top/tree/website/_data/locations) you'll see that the update process for this weekend has started and there's a lot of regions to go through before reaching Syria :slightly_smiling_face: 

The thing is, the [GraphQL queries currently used in github.go](https://github.com/ashkulz/committers.top/blob/e8ae7af6080ab215ea225d1c4700db4eb6e89233/github/github.go#L89) take a long time to run -- just running it for all regions [via GitHub actions takes ~2 days](https://github.com/ashkulz/committers.top/commits/website) -- most of [the failures](https://github.com/ashkulz/committers.top/actions/workflows/weekly_update.yml?query=is%3Afailure) are due to [hitting the GraphQL rate limits](https://docs.github.com/en/graphql/overview/resource-limitations#rate-limit), which means you can't run it more often (e.g. every 2/3 days) without abusing GitHub Actions :man_shrugging:

**Comment by ashkulz** [comment]
In case it isn't updated by tomorrow EOD, please let me know.

**Comment by ashkulz** [comment]
It's updated and now you're at the 1st position :grin:

**Comment by karam-mustafa** [comment]
@ashkulz Yes I saw it, Thanks a lot 🎉
